goals:
  - pose:
      x: 0.0
      y: 3.0
      yaw: 0.0  # Degrees
  - pose:
      x: 6.0
      y: 4.0
      yaw: 30.0  # Degrees
  - pose:
      x: 6.5
      y: -1.4
      yaw: 180.0  # Degrees
  - pose:
      x: -1.6
      y: -2.5
      yaw: 75.0  # Degrees
